version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/sideeye

    steps:
      - checkout

      - run:
          name: setup venv
          command: |
            python3 -m venv venv

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test
