version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/sideeye

    steps:
      - checkout

      - run:
          name: run tests
          command: make test
